### ISSUE TITLE
This failed for me during `docker build`:

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/mesh-adaptation-docs#44]
This failed for me during `docker build`:
```
0.839 apt-get not found or disabled. Proceeding on the rash assumption that your compiled dependencies are in place.
0.839 Please use the --show-dependencies for more information.
0.839 Creating firedrake venv in '/home/firedrake/firedrake'.
20.59 BLAS config is {}
20.59 Configuration saved to /home/firedrake/firedrake/.configuration.json
20.59 Cloning firedrake
20.59 
35.05 Successfully cloned repository firedrake.
35.05 Checking out branch master
35.13 Successfully checked out branch master
35.13 Updating submodules.
35.14 Successfully updated submodules.
35.14 Creating firedrake-update script.
35.15 Pip installing VTK to venv
35.48 Traceback (most recent call last):
35.48   File "/home/firedrake/firedrake-install", line 1793, in <module>
35.48     run_pip_install_wrap(["vtk>=9.0.1"], {})
35.48   File "/home/firedrake/firedrake-install", line 1007, in run_pip_install_wrap
35.48     run_pip_install([req])
35.48   File "/home/firedrake/firedrake-install", line 991, in run_pip_install
35.48     check_call(pipinstall + pipargs)
35.48   File "/home/firedrake/firedrake-install", line 672, in check_call
35.48     log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
35.48               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
35.48   File "/usr/lib/python3.12/subprocess.py", line 466, in check_output
35.48     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
35.48            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
35.48   File "/usr/lib/python3.12/subprocess.py", line 571, in run
35.49     raise CalledProcessError(retcode, process.args,
35.49 subprocess.CalledProcessError: Command '['/home/firedrake/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,numpy', '-v', 'vtk>=9.0.1']' returned non-zero exit status 1.
```

_Originally posted by @ddundo in https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/40#discussion_r1745457385_

**Comment by ddundo** [comment]
Just tried this again and got the same error. I wouldn't be surprised if it's just an M1 issue, but would be nice to test it. I think we can do that by passing `platform` to the docker build action in the workflow (see https://docs.docker.com/engine/reference/commandline/buildx_build/#platform)
